# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeM8JjIDqrese-TNFJFr8kJGkq1E01Aq
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv('Advertising_F.csv')
df.head()

import streamlit as st
import pandas as pd
import plotly.express as px

st.title('Advertising Dashboard_Adam_Morkous')
st.sidebar.markdown("Filters")
x_var=st.sidebar.selectbox("X-Axis",['TV','radio','newspaper'])
y_var=st.sidebar.selectbox("Y-Axis",['sales'])

fig=px.scatter(df,x=x_var,y=y_var,trendline='ols')
st.plotly_chart(fig)
#Show the data frame
st.write('### Data Frame')
st.write(df)

#Lets show a map
st.title("I'm the Map!!!")
fig=px.scatter_mapbox(df,lat='latitude',lon='longitude',color='sales',
                      size='TV', hover_name='City')
fig.update_layout(mapbox_style='carto-positron')
st.plotly_chart(fig)
